---
name: Object-LocalVars
version: 0.19
author:
  - 'David A Golden <dagolden@cpan.org>'
abstract: |-
  Outside-in objects with local aliasing of $self and object
  variables
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Exporter: 0
  Scalar::Util: 1.09
  perl: 5.008
  subs: 0
build_requires:
  Data::Dumper: 0
  Test::Exception: 0
  Test::More: 0.48
  base: 0
  overload: 0
provides:
  Object::LocalVars:
    file: lib/Object/LocalVars.pm
    version: 0.19
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  dir:
    - examples
