---
abstract: 'Outside-in objects with local aliasing of $self and object variables'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Data::Dumper: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec::Functions: '0'
  List::Util: '0'
  Test::Exception: '0'
  Test::More: '0'
  base: '0'
  blib: '0'
  overload: '0'
  version: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Object-LocalVars
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Object::LocalVars:
    file: lib/Object/LocalVars.pm
    version: '0.21'
requires:
  Carp: '0'
  Exporter: '0'
  Scalar::Util: '1.09'
  perl: '5.008'
  strict: '0'
  subs: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/dagolden/Object-LocalVars/issues
  homepage: https://github.com/dagolden/Object-LocalVars
  repository: https://github.com/dagolden/Object-LocalVars.git
version: '0.21'
x_authority: cpan:DAGOLDEN
