---
name: Object-LocalVars
version: 0.12
author:
  - David A Golden <dagolden@cpan.org>
abstract: |-
  Outside-in objects with local aliasing of $self and object
  variables
license: perl
requires:
  Test::Exception: 0
  Test::More: 0.47
  perl: 5.006
provides:
  Object::LocalVars:
    file: lib/Object/LocalVars.pm
    version: 0.12
generated_by: Module::Build version 0.2702
noindex:
  directory:
    - examples
